TestSuite[{
	"Scoping.mt",
	"ScopingNested.mt",
	"Patterns.mt",
	"PatternsNested.mt",
	"PatternsDelayed.mt",
	"PatternsDelayedNested.mt",
	"Function.mt",
	"Functions.mt",
	"FunctionsNested.mt",
	"Strings.mt",
	"MixedNested.mt",
	"InputFormBoxes.mt",
	"FormattingWhitespace.mt"
}]